server:
  port: 8080
spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  liquibase:
    change-log: 'classpath:db/changelog/changeLog.xml'
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect